
augmentConfigs : 
  input_size : 256
  color_jitter : None
  auto_augment : rand-m9-mstd0.5-inc1
  # RE 的意思是 random eraser
  reprob : 0
  remode : pixel
  recount : 1

train_rootPath : /home/zengshimao/code/Super-Resolution-Neural-Operator/data/validation
validation_rootPath : /home/zengshimao/code/Super-Resolution-Neural-Operator/data/validation
lable_path : /home/zengshimao/code/Super-Resolution-Neural-Operator/test/ILSVRC2012_validation_ground_truth.txt
train_batchsize : 24
val_batchsize : 16 


eval_type: div2k-2
eval_bsize: 500


# data_norm:
#   inp: {sub: [0.5], div: [0.5]}
#   gt: {sub: [0.5], div: [0.5]}

model:
  name: random_N_Classifitor
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    width: 256
    blocks: 16
    

optimizer:
  name: adam
  args:
    lr: 1.00e-03 #不用管，后面会替换
    #weight_decay: 1.e-5
epoch_max: 30
warmup_step_lr:
  multiplier: 1
  total_epoch: 5

base_lr : 1.00e-03
#multi_step_lr:
#  milestones: [200, 400, 600, 800, 1000]
#  gamma: 0.5


#resume: /home/zengshimao/code/Super-Resolution-Neural-Operator/result/finetune-debug-epoch2.pth
finetune : /home/zengshimao/code/Super-Resolution-Neural-Operator/result/patchAttention-epoch40.pth
epoch_val: 1
epoch_save: 1

