train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data/test
      repeat: 1
      # first_k : 5000
      
  wrapper: 
    name: random-n-dataloader
    args:
      point_num: 8000
      augment: True
      istrain: True
      augmentConfigs : 
        input_size : 224
        color_jitter : None
        auto_augment : rand-m9-mstd0.5-inc1
        # RE 的意思是 random eraser
        reprob : 0
        remode : pixel
        recount : 1
  batch_size: 32
  num_workers: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data/task3
  wrapper:
    name: random-n-dataloader
    args:
      point_num: 8000
      augment: True
      istrain: True
      augmentConfigs : 
        input_size : 224
        color_jitter : None
        auto_augment : rand-m9-mstd0.5-inc1
        # RE 的意思是 random eraser
        reprob : 0
        remode : pixel
        recount : 1
  batch_size: 24
eval_type: div2k-2
eval_bsize: 500

# data_norm:
#   inp: {sub: [0.5], div: [0.5]}
#   gt: {sub: [0.5], div: [0.5]}

model:
  name: random_N_encoder
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    width: 224
    blocks: 16

optimizer:
  name: adam
  args:
    lr: 1.00e-03 
    #weight_decay: 1.e-5
epoch_max: 30
warmup_step_lr:
  multiplier: 1
  total_epoch: 5
#multi_step_lr:
#  milestones: [200, 400, 600, 800, 1000]
#  gamma: 0.5

base_lr : 1.00e-03
# resume: /home/zengshimao/code/Super-Resolution-Neural-Operator/result/_train-randomN/epoch-last.pth
epoch_val: 10
epoch_save: 10

